#!/bin/bash
# pack-bundle.sh — Cavli-side: build a /pkg toolchain bundle and publish it.
#
# Run this on a machine that already has a known-good /pkg (the CI host is the
# reference). It produces a versioned, checksummed archive and optionally
# uploads it to the Drive folder that cqm22x-setup.sh downloads from.
#
# Customers never run this. They only consume the output.
#
#   ./pack-bundle.sh --version 1.0.0 --source /pkg --upload
#
# Layout inside the archive:
#   qct/software/{HEXAGON_Tools,arm,llvm}
#   sectools/
#   prebuilts/
#   BUNDLE_VERSION
#   SHA256SUMS.spot        sampled checksums, verified by cqm-doctor at runtime
#   MANIFEST.txt           human-readable inventory with sizes and provenance

set -euo pipefail

VERSION=""
SOURCE=/pkg
OUTDIR="${PWD}"
STAGE_DIR=""          # defaults to $OUTDIR/.stage — see below
ZSTD_LEVEL=15
UPLOAD=no
SPOT_COUNT=200
RCLONE_REMOTE="${CQM_RCLONE_REMOTE:-GGDrive}"
RCLONE_CONFIG_FILE="${CQM_RCLONE_CONFIG:-$HOME/rclone_fw_share.conf}"
REMOTE_DIR="${CQM_BUNDLE_REMOTE_DIR:-/cqm22x-buildenv/toolchain}"

log()  { printf '\e[36m==>\e[0m %s\n' "$*"; }
die()  { printf '\e[31m==> %s\e[0m\n' "$*" >&2; exit 1; }

declare -A MAP=()

usage() {
cat <<EOF
pack-bundle.sh --version V [options]

  --version V        bundle version, e.g. 1.0.0            (required)
  --source DIR       /pkg tree to pack from                (default $SOURCE)
  --map REL=DIR      take REL from DIR instead of \$SOURCE/REL (repeatable)
  --outdir DIR       where to write the archive            (default \$PWD)
  --stage-dir DIR    staging area, needs ~50 GB free       (default OUTDIR/.stage)
  --level N          zstd compression level                (default $ZSTD_LEVEL)
  --upload           upload archive + checksum to Drive afterwards
  --spot-count N     files to sample for SHA256SUMS.spot   (default $SPOT_COUNT)
  --remote-dir P     Drive folder                          (default $REMOTE_DIR)

Staging defaults to a directory beside the output rather than /tmp: the tree is
around 50 GB, and /tmp is frequently a tmpfs sized well below that.

--map exists because a reference /pkg is not always assembled in one place.
On a host where the toolchain lives in a checkout and the prebuilts came from
somewhere else:

  ./pack-bundle.sh --version 1.0.0 \\
      --source /srv/sdx_buildtools \\
      --map prebuilts=/srv/rescue/pkg/kernel/prebuilts
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)    VERSION="$2"; shift 2;;
        --source)     SOURCE="$2"; shift 2;;
        --map)        [[ "$2" == *=* ]] || die "--map expects REL=DIR, got: $2"
                      MAP["${2%%=*}"]="${2#*=}"; shift 2;;
        --outdir)     OUTDIR="$2"; shift 2;;
        --stage-dir)  STAGE_DIR="$2"; shift 2;;
        --level)      ZSTD_LEVEL="$2"; shift 2;;
        --upload)     UPLOAD=yes; shift;;
        --spot-count) SPOT_COUNT="$2"; shift 2;;
        --remote-dir) REMOTE_DIR="$2"; shift 2;;
        -h|--help)    usage; exit 0;;
        *) die "unknown option: $1";;
    esac
done

[[ -n "$VERSION" ]] || { usage; die "--version is required"; }

# Only these subtrees go into the bundle. Everything else under /pkg is either
# generated by builds (openwrt build_dir, yocto downloads) or supplied by the
# public image (tools/dtc, qct/software/boottools).
INCLUDE=(
    qct/software/HEXAGON_Tools
    qct/software/arm
    qct/software/llvm
    sectools
    prebuilts
)

# Resolve each include to a real directory, honouring --map.
declare -A SRC_OF=()
for p in "${INCLUDE[@]}"; do
    src="${MAP[$p]:-$SOURCE/$p}"
    [[ -d "$src" ]] || die "source for '$p' is missing: $src"
    SRC_OF["$p"]="$src"
done

mkdir -p "$OUTDIR"
: "${STAGE_DIR:=$OUTDIR/.stage}"
mkdir -p "$STAGE_DIR"

# Fail before spending an hour copying, not after.
need_kb=0
for p in "${INCLUDE[@]}"; do
    need_kb=$(( need_kb + $(du -sk "${SRC_OF[$p]}" | cut -f1) ))
done
have_kb="$(df -Pk "$STAGE_DIR" | awk 'NR==2{print $4}')"
log "staging needs $(( need_kb / 1024 / 1024 )) GB, $STAGE_DIR has $(( have_kb / 1024 / 1024 )) GB free"
(( have_kb > need_kb + 5*1024*1024 )) \
    || die "not enough space at $STAGE_DIR — pass --stage-dir pointing somewhere larger"

STAGE="$(mktemp -d -p "$STAGE_DIR" "pack-${VERSION}.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT
# mktemp creates the directory 0700, and tar records that mode for "." — which
# then lands on the recipient's extracted bundle directory.
chmod 0755 "$STAGE"
log "staging at $STAGE"

for p in "${INCLUDE[@]}"; do
    log "copying $p  <-  ${SRC_OF[$p]}"
    mkdir -p "$STAGE/$(dirname "$p")"
    # Trailing slash on the source, explicit destination: the content lands at
    # $STAGE/$p regardless of what the source directory happens to be called.
    rsync -aH --numeric-ids "${SRC_OF[$p]}/" "$STAGE/$p/"
done

printf '%s\n' "$VERSION" > "$STAGE/BUNDLE_VERSION"

# --- inventory --------------------------------------------------------------
log "writing MANIFEST.txt"
{
    echo "CQM22x toolchain bundle $VERSION"
    echo "packed from : $SOURCE"
    echo "packed on   : $(hostname)"
    echo
    echo "contents:"
    for p in "${INCLUDE[@]}"; do
        printf '  %-42s %s\n' "$p" "$(du -sh "$STAGE/$p" | cut -f1)"
    done
    echo
    echo "component versions:"
    [[ -d "$STAGE/qct/software/HEXAGON_Tools" ]] && \
        printf '  HEXAGON_Tools : %s\n' "$(ls "$STAGE/qct/software/HEXAGON_Tools" | tr '\n' ' ')"
    [[ -d "$STAGE/qct/software/llvm/release/arm" ]] && \
        printf '  llvm (arm)    : %s\n' "$(ls "$STAGE/qct/software/llvm/release/arm" | tr '\n' ' ')"
    echo
    echo "This archive contains Qualcomm proprietary toolchains and is supplied"
    echo "under the recipient's licence agreement. Do not redistribute."
} > "$STAGE/MANIFEST.txt"

# --- spot checksums ---------------------------------------------------------
# A full checksum of ~50 GB takes long enough that nobody would run it. A
# deterministic sample of executables catches truncated or partial extractions,
# which is the failure mode that actually happens, and runs in seconds.
log "sampling $SPOT_COUNT files for SHA256SUMS.spot"
(
    cd "$STAGE"
    # Sorted then strided, so the sample is reproducible and spread across the tree.
    find "${INCLUDE[@]}" -type f \( -perm -u+x -o -name '*.so*' \) 2>/dev/null \
        | LC_ALL=C sort \
        | awk -v n="$SPOT_COUNT" 'BEGIN{c=0} {a[++c]=$0} END{
              if (c==0) exit;
              step = (c>n) ? int(c/n) : 1;
              for (i=1; i<=c; i+=step) print a[i];
          }' \
        | xargs -d '\n' -r sha256sum > SHA256SUMS.spot
    printf '  %s files\n' "$(wc -l < SHA256SUMS.spot)"
)

# --- archive ----------------------------------------------------------------
ARCHIVE="$OUTDIR/cqm22x-pkg-${VERSION}.tar.zst"
log "creating $ARCHIVE at zstd -$ZSTD_LEVEL (this takes a while)"
tar --use-compress-program="zstd -${ZSTD_LEVEL} -T0 --long=27" \
    -cf "$ARCHIVE" -C "$STAGE" .

log "checksumming archive"
# Run from OUTDIR so the file records a bare filename: the consumer downloads
# the archive under its own path and checks it there.
( cd "$OUTDIR" && sha256sum "$(basename "$ARCHIVE")" ) > "$ARCHIVE.sha256"

printf '\n  archive  %s\n  size     %s\n  sha256   %s\n\n' \
    "$ARCHIVE" "$(du -h "$ARCHIVE" | cut -f1)" "$(awk '{print $1}' "$ARCHIVE.sha256")"

# --- upload -----------------------------------------------------------------
if [[ "$UPLOAD" == yes ]]; then
    command -v rclone >/dev/null 2>&1 || die "rclone not found"
    [[ -r "$RCLONE_CONFIG_FILE" ]] || die "rclone config not readable: $RCLONE_CONFIG_FILE"
    log "uploading to ${RCLONE_REMOTE}:${REMOTE_DIR}"
    rclone --config "$RCLONE_CONFIG_FILE" --progress --transfers 4 --retries 5 \
        copy "$ARCHIVE" "${RCLONE_REMOTE}:${REMOTE_DIR}/"
    rclone --config "$RCLONE_CONFIG_FILE" \
        copy "$ARCHIVE.sha256" "${RCLONE_REMOTE}:${REMOTE_DIR}/"
    log "uploaded. Customers install it with:"
    printf '\n    ./cqm22x-setup.sh --bundle-version %s\n\n' "$VERSION"
fi
